# Generated by Django 4.2 on 2023-05-02 16:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.CharField(max_length=15)),
                ('base', models.CharField(max_length=10)),
                ('create_year', models.IntegerField()),
                ('manager_phone', models.CharField(max_length=15)),
                ('manager_last_name', models.CharField(max_length=15)),
                ('manager_first_name', models.CharField(max_length=15)),
                ('manager_middle_name', models.CharField(max_length=20)),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='footballclub.city')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='EnemyTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=15)),
                ('coach_last_name', models.CharField(max_length=15)),
                ('coach_first_name', models.CharField(max_length=15)),
                ('coach_middle_name', models.CharField(max_length=20)),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='footballclub.country')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals_skipped', models.IntegerField()),
                ('game_date', models.DateField(default=django.utils.timezone.now)),
                ('club_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='footballclub.club')),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='footballclub.country')),
                ('enemyteam_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='footballclub.enemyteam')),
            ],
        ),
        migrations.CreateModel(
            name='GameLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_level', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=15)),
                ('first_name', models.CharField(max_length=15)),
                ('middle_name', models.CharField(max_length=20)),
                ('birth_date', models.DateField(default=django.utils.timezone.now)),
                ('year_fact', models.IntegerField()),
                ('photo', models.ImageField(upload_to='')),
                ('cost', models.IntegerField()),
                ('club_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='footballclub.club')),
                ('position_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='footballclub.position')),
            ],
        ),
        migrations.CreateModel(
            name='GameAttend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals_scored', models.IntegerField()),
                ('attend', models.BooleanField()),
                ('salary', models.IntegerField()),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='footballclub.game')),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='footballclub.player')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='gamelevel_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='footballclub.gamelevel'),
        ),
        migrations.AddField(
            model_name='club',
            name='league_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='footballclub.league'),
        ),
    ]
