# Generated by Django 4.2 on 2023-05-09 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('footballclub', '0001_initial'),
    ]

    operations = [
    ]
