# Generated by Django 4.2 on 2023-05-09 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('footballclub', '0002_auto_20230509_1603'),
    ]

    operations = [
    ]
