# Generated by Django 4.2 on 2023-05-09 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('footballclub', '0004_auto_20230509_1613'),
    ]

    operations = [
    ]
