# Generated by Django 4.2 on 2023-07-14 15:05

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import footballclub.models


class Migration(migrations.Migration):

    dependencies = [
        ('footballclub', '0005_auto_20230509_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='city',
            field=models.CharField(max_length=10, validators=[footballclub.models.validate_string], verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='club',
            name='base',
            field=models.CharField(max_length=20, verbose_name='Training base'),
        ),
        migrations.AlterField(
            model_name='club',
            name='city_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='footballclub.city', verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='club',
            name='club',
            field=models.CharField(max_length=15, verbose_name='Club name'),
        ),
        migrations.AlterField(
            model_name='club',
            name='create_year',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(2023)], verbose_name='Create year'),
        ),
        migrations.AlterField(
            model_name='club',
            name='league_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='footballclub.league', verbose_name='Лига'),
        ),
        migrations.AlterField(
            model_name='club',
            name='manager_first_name',
            field=models.CharField(max_length=15, validators=[footballclub.models.validate_string], verbose_name='Manager`s first name'),
        ),
        migrations.AlterField(
            model_name='club',
            name='manager_last_name',
            field=models.CharField(max_length=15, validators=[footballclub.models.validate_string], verbose_name='Manager`s last name'),
        ),
        migrations.AlterField(
            model_name='club',
            name='manager_middle_name',
            field=models.CharField(blank=True, max_length=20, validators=[footballclub.models.validate_string], verbose_name='Manager`s middle name'),
        ),
        migrations.AlterField(
            model_name='club',
            name='manager_phone',
            field=models.CharField(max_length=15, validators=[footballclub.models.validate_phone], verbose_name='Manager`s phone'),
        ),
        migrations.AlterField(
            model_name='country',
            name='country',
            field=models.CharField(max_length=10, validators=[footballclub.models.validate_string], verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='enemyteam',
            name='coach_first_name',
            field=models.CharField(max_length=15, validators=[footballclub.models.validate_string], verbose_name='Coach first name'),
        ),
        migrations.AlterField(
            model_name='enemyteam',
            name='coach_last_name',
            field=models.CharField(max_length=15, validators=[footballclub.models.validate_string], verbose_name='Coach last name'),
        ),
        migrations.AlterField(
            model_name='enemyteam',
            name='coach_middle_name',
            field=models.CharField(blank=True, max_length=20, validators=[footballclub.models.validate_string], verbose_name='Coach middle name'),
        ),
        migrations.AlterField(
            model_name='enemyteam',
            name='country_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='footballclub.country', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='enemyteam',
            name='team_name',
            field=models.CharField(max_length=15, validators=[footballclub.models.validate_string], verbose_name='Enemy team name'),
        ),
        migrations.AlterField(
            model_name='game',
            name='club_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='footballclub.club', verbose_name='Club'),
        ),
        migrations.AlterField(
            model_name='game',
            name='country_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='footballclub.country', verbose_name='Country of the game'),
        ),
        migrations.AlterField(
            model_name='game',
            name='enemyteam_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='footballclub.enemyteam', verbose_name='Enemy team'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_date',
            field=models.DateField(default=django.utils.timezone.now, validators=[django.core.validators.MaxValueValidator(datetime.date(2023, 7, 14))], verbose_name='Date of the game'),
        ),
        migrations.AlterField(
            model_name='game',
            name='gamelevel_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='footballclub.gamelevel', verbose_name='Game Level'),
        ),
        migrations.AlterField(
            model_name='game',
            name='goals_skipped',
            field=models.PositiveIntegerField(verbose_name='Goals skipped'),
        ),
        migrations.AlterField(
            model_name='gameattend',
            name='attend',
            field=models.BooleanField(verbose_name='Was there any participation'),
        ),
        migrations.AlterField(
            model_name='gameattend',
            name='game_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='footballclub.game', verbose_name='Game'),
        ),
        migrations.AlterField(
            model_name='gameattend',
            name='goals_scored',
            field=models.PositiveIntegerField(verbose_name='Goals scored'),
        ),
        migrations.AlterField(
            model_name='gameattend',
            name='player_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='footballclub.player', verbose_name='Player'),
        ),
        migrations.AlterField(
            model_name='gameattend',
            name='salary',
            field=models.PositiveIntegerField(verbose_name='Game award ($)'),
        ),
        migrations.AlterField(
            model_name='gamelevel',
            name='game_level',
            field=models.CharField(max_length=25, verbose_name='Game level'),
        ),
        migrations.AlterField(
            model_name='league',
            name='league',
            field=models.CharField(max_length=20, verbose_name='League name'),
        ),
        migrations.AlterField(
            model_name='player',
            name='birth_date',
            field=models.DateField(default=django.utils.timezone.now, validators=[footballclub.models.validate_birth_date], verbose_name='Birth date'),
        ),
        migrations.AlterField(
            model_name='player',
            name='club_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='footballclub.club', verbose_name='Club'),
        ),
        migrations.AlterField(
            model_name='player',
            name='cost',
            field=models.PositiveIntegerField(verbose_name='Contract cost ($)'),
        ),
        migrations.AlterField(
            model_name='player',
            name='first_name',
            field=models.CharField(max_length=15, validators=[footballclub.models.validate_string], verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='player',
            name='last_name',
            field=models.CharField(max_length=15, validators=[footballclub.models.validate_string], verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='player',
            name='middle_name',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[footballclub.models.validate_string], verbose_name='Middle name'),
        ),
        migrations.AlterField(
            model_name='player',
            name='photo',
            field=models.ImageField(blank=True, upload_to='static/img', verbose_name='Player`s photo'),
        ),
        migrations.AlterField(
            model_name='player',
            name='position_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='footballclub.position', verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='player',
            name='year_fact',
            field=models.PositiveIntegerField(validators=[footballclub.models.validate_year_fact, django.core.validators.MaxValueValidator(2023)], verbose_name='Year of joining the club'),
        ),
        migrations.AlterField(
            model_name='position',
            name='position',
            field=models.CharField(max_length=15, verbose_name='Position'),
        ),
    ]
