# Generated by Django 4.2 on 2023-07-14 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('footballclub', '0007_alter_club_manager_middle_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='manager_middle_name',
        ),
        migrations.RemoveField(
            model_name='enemyteam',
            name='coach_middle_name',
        ),
        migrations.RemoveField(
            model_name='player',
            name='middle_name',
        ),
    ]
