# Generated by Django 4.2 on 2023-07-14 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('footballclub', '0008_remove_club_manager_middle_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='league_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='footballclub.league', verbose_name='Лига'),
        ),
        migrations.AlterField(
            model_name='game',
            name='gamelevel_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='footballclub.gamelevel', verbose_name='Game Level'),
        ),
        migrations.AlterField(
            model_name='player',
            name='club_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='footballclub.club', verbose_name='Club'),
        ),
        migrations.AlterField(
            model_name='player',
            name='position_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='footballclub.position', verbose_name='Position'),
        ),
    ]
