from django.urls import path
from .views import players_list, PlayerInfo, ClubInfo, clubs_list,\
    games_list, GameInfo, positions_list, countries_list, cities_list,\
    leagues_list, gamelevels_list, PlayerCreateView, PlayerUpdateView, PlayerDeleteView, \
    ClubCreateView, ClubUpdateView, ClubDeleteView, GameCreateView, GameUpdateView, GameDeleteView,\
    PositionCreateView, PositionUpdateView, PositionDeleteView, CountryCreateView, CountryUpdateView, CountryDeleteView,\
    CityCreateView, CityUpdateView, CityDeleteView, LeagueCreateView, LeagueUpdateView, LeagueDeleteView,\
    GameLevelCreateView, GameLevelUpdateView, GameLevelDeleteView, EnemyTeamCreateView, EnemyTeamUpdateView, EnemyTeamDeleteView,\
    GameAttendCreateView, GameAttendUpdateView, GameAttendDeleteView, CreateListView, Search, ClubRatingView, PlayerStatsView,\
    ClubStatsView, gamecount_view, finances_view, player_rating_view, gameattended_list, enemyteam_list, clubs_by_cities,\
    enemies_by_countries, players_by_club, players_above_average, above_average_by_club, club_games

urlpatterns = [
    path('', players_list, name='index'),
    path('players/', players_list, name='players'),
    path('players/<int:pk>', PlayerInfo.as_view(), name='player_info'),
    path('clubs/', clubs_list, name='clubs'),
    path('clubs/<int:pk>', ClubInfo.as_view(), name='club_info'),
    path('games/', games_list, name='games'),
    path('games/<int:pk>', GameInfo.as_view(), name='game_info'),
    path('positions#<int:id>', positions_list, name='positions'),
    path('countries#<int:id>', countries_list, name='countries'),
    path('cities#<int:id>', cities_list, name='cities'),
    path('leagues#<int:id>', leagues_list, name='leagues'),
    path('gamelevels#<int:id>', gamelevels_list, name='gamelevels'),
    path('enemy_teams#<int:id>', enemyteam_list, name='enemy_teams'),
    path('game_attended#<int:id>',
         gameattended_list, name='game_attended'),
    path('players/create/', PlayerCreateView.as_view(), name='players_create'),
    path('players/<int:pk>/update/',
         PlayerUpdateView.as_view(), name='players_update'),
    path('players/<int:pk>/delete/',
         PlayerDeleteView.as_view(), name='players_delete'),
    path('clubs/create/', ClubCreateView.as_view(), name='clubs_create'),
    path('clubs/<int:pk>/update/', ClubUpdateView.as_view(), name='clubs_update'),
    path('clubs/<int:pk>/delete/', ClubDeleteView.as_view(), name='clubs_delete'),
    path('games/create/', GameCreateView.as_view(), name='games_create'),
    path('games/<int:pk>/update/', GameUpdateView.as_view(), name='games_update'),
    path('games/<int:pk>/delete/', GameDeleteView.as_view(), name='games_delete'),
    path('positions/create/', PositionCreateView.as_view(), name='positions_create'),
    path('positions/<int:pk>/update/',
         PositionUpdateView.as_view(), name='positions_update'),
    path('positions/<int:pk>/delete/',
         PositionDeleteView.as_view(), name='positions_delete'),
    path('countries/create/', CountryCreateView.as_view(), name='countries_create'),
    path('countries/<int:pk>/update/',
         CountryUpdateView.as_view(), name='countries_update'),
    path('countries/<int:pk>/delete/',
         CountryDeleteView.as_view(), name='countries_delete'),
    path('cities/create/', CityCreateView.as_view(), name='cities_create'),
    path('cities/<int:pk>/update/',
         CityUpdateView.as_view(), name='cities_update'),
    path('cities/<int:pk>/delete/',
         CityDeleteView.as_view(), name='cities_delete'),
    path('leagues/create/', LeagueCreateView.as_view(), name='leagues_create'),
    path('leagues/<int:pk>/update/',
         LeagueUpdateView.as_view(), name='leagues_update'),
    path('leagues/<int:pk>/delete/',
         LeagueDeleteView.as_view(), name='leagues_delete'),
    path('gamelevels/create/', GameLevelCreateView.as_view(),
         name='gamelevels_create'),
    path('gamelevels/<int:pk>/update/',
         GameLevelUpdateView.as_view(), name='gamelevels_update'),
    path('gamelevels/<int:pk>/delete/',
         GameLevelDeleteView.as_view(), name='gamelevels_delete'),
    path('enemy_teams/create/', EnemyTeamCreateView.as_view(),
         name='enemy_teams_create'),
    path('enemy_teams/<int:pk>/update/',
         EnemyTeamUpdateView.as_view(), name='enemy_teams_update'),
    path('enemy_teams/<int:pk>/delete/',
         EnemyTeamDeleteView.as_view(), name='enemy_teams_delete'),
    path('game_attended/create/', GameAttendCreateView.as_view(),
         name='game_attended_create'),
    path('game_attended/<int:pk>/update/',
         GameAttendUpdateView.as_view(), name='game_attended_update'),
    path('game_attended/<int:pk>/delete/',
         GameAttendDeleteView.as_view(), name='game_attended_delete'),
    path('create_item/', CreateListView.as_view(), name='create_item'),
    path('search/', Search.as_view(), name='search'),
    path('rating/', ClubRatingView.as_view(), name='rating'),
    path('rating/club_rating', ClubRatingView.as_view(), name='club_rating'),
    path('rating/player_rating', player_rating_view, name='player_rating'),
    path('stats/', ClubStatsView.as_view(), name='stats'),
    path('stats/club_stats', ClubStatsView.as_view(), name='club_stats'),
    path('stats/player_stats', PlayerStatsView.as_view(), name='player_stats'),
    path('slices/', gamecount_view, name='slices'),
    path('slices/game_count/', gamecount_view, name='game_count'),
    path('slices/finances/', finances_view, name='finances'),
    path('clubs_by_cities/', clubs_by_cities, name='clubs_by_cities'),
    path('enemies_by_countries/', enemies_by_countries,
         name='enemies_by_countries'),
    path('players_by_club', players_by_club, name='players_by_club'),
    path('stats/players_above_average',
         players_above_average, name='players_above_average'),
    path('stats/players_above_average/general',
         players_above_average, name='players_above_average'),
    path('stats/players_above_average/by_club',
         above_average_by_club, name='above_average_by_club'),
    path('stats/club_stats/club_games', club_games, name='club_games')
]
